site:
  title: GitSite
  description: GitSite is a static web site generator for Git.
  keywords: gitsite, git, static web site, html
  theme: default
  navigation:
    - title: User Guide
      type: book
      ref: gitsite-guide
    - title: Blogs
      type: blog
    - title: About GitSite
      type: page
      ref: about
    - title: Github
      type: link
      ref: https://github.com/michaelliao/gitsite
      external: true
    - title: Go To GitLab
      type: link
      ref: https://github.com/michaelliao/gitsite
      external: true
    - title: Build Your Own Sqlite From Scratch
      type: link
      ref: https://github.com/michaelliao/gitsite
      external: true
    - title: Git Repository
      type: link
      ref: https://github.com/michaelliao/gitsite
      external: true
    - title: Discuss
      type: link
      ref: https://github.com/michaelliao/gitsite
      external: true
  contact:
    name: Michael Liao
    github: https://github.com/michaelliao/gitsite
    twitter: https://twitter.com/liaoxuefeng
  blogs:
    title: Latest Updates
  books:
    index-marker: true

  search:
    # search by lunr or semantic:
    engine: lunr
    languages:
      - en
      - zh

build:
  # copy special files under root dir (ignore if not found):
  copy:
    - favicon.ico
    - robots.txt
    - ads.txt

# you can add any items:
